      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=MatiasRivas1_Tecnolocos
            -Dsonar.organization=lau16-bit
            -Dsonar.token=172a68eb1480f027c05586e4f062ff14bdbe8139
