sonar.projectKey=MatiasRivas1_Tecnolocos
sonar.organization=lau16-bit
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/venv/**,**/tests/**,**/__pycache__/**,**/*.pyc,**/features/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-reports.xml

sonar.language=py
